### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ElTuna** [BlueDevelopersInc/DiscordSRVUtils#103]
**Describe the bug**
The plugin doesn't start and when i run /pl its show in red color

**To Reproduce**
i just started the server and i got this in console:
```
 DiscordSRV encountered an unknown Discord error: 20001: Bots cannot use this endpoint
```

**Server Information:**
 - Version: 1.18.2
 - Software: Paper

**Plugin Information:**
 - Version: 1.2.8
 - DiscordSRV Version: 1.26.0-SNAPSHOT
 - Build Number: none (but i get this when i run /dsu
```
Unexpected exception while parsing console command "dsu"
org.bukkit.command.CommandException: Cannot execute command 'dsu' in plugin DiscordSRVUtils v1.2.8 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869)
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:510)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:484)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by BlueTree242** [comment]
Hi, there is an error in your console just search for it in the logs, when enabling the plugin, please send it here

**Comment by BlueTree242** [comment]
The error "Bots cannot use this endpoint" is not caused by discordsrvutils, update all any discordsrv addons you have

**Comment by ElTuna** [comment]
console log is large
```
[19:06:57 INFO]: 
[]=====[Enabling DiscordSRVUtils]=====[]
| Information:
|   Name: DiscordSRVUtils
|   Developers: BlueTree242
|   Version: 1.2.8
|   Storage: MySQL
| Support:
|   Github: https://github.com/BlueTree242/BlueDevelopersInc/issues
|   Discord: https://discordsrvutils.xyz/support
[]================================[]
[19:06:57 INFO]: [DiscordSRVUtils] [HikariCP] HikariPool-1 - Starting...
[19:06:57 INFO]: [DiscordSRV] [JDA] Login Successful!
[19:06:58 INFO]: [DiscordSRV] [JDA] Connected to WebSocket
[19:06:58 ERROR]: [DiscordSRVUtils] [HikariCP] HikariPool-1 - Exception during pool initialization.
[19:06:58 INFO]: [DiscordSRV] API listener tk.bluetree242.discordsrvutils.listeners.discordsrv.DiscordSRVListener anulado
[19:06:58 WARN]: [DiscordSRVUtils] Plugin could not start
[19:06:58 ERROR]: Error occurred while enabling DiscordSRVUtils v1.2.8 (Is it up to date?)
java.lang.NoSuchMethodError: 'github.scarsz.discordsrv.objects.threads.ConsoleMessageQueueWorker github.scarsz.discordsrv.DiscordSRV.getConsoleMessageQueueWorker()'
        at tk.bluetree242.discordsrvutils.bukkit.BukkitDebugger.run(BukkitDebugger.java:72) ~[DiscordSRVUtils-1.2.8.jar:?]
        at tk.bluetree242.discordsrvutils.ErrorHandler.startupError(ErrorHandler.java:47) ~[DiscordSRVUtils-1.2.8.jar:?]
        at tk.bluetree242.discordsrvutils.DiscordSRVUtils.onEnable(DiscordSRVUtils.java:244) ~[DiscordSRVUtils-1.2.8.jar:?]
        at tk.bluetree242.discordsrvutils.bukkit.DiscordSRVUtilsBukkit.onEnable(DiscordSRVUtilsBukkit.java:51) ~[DiscordSRVUtils-1.2.8.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-310]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-310]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-310]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-310]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-310]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-310]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-310]
        at java.lang.Thread.run(Thread.java:833) ~[?:?
```

**Comment by BlueTree242** [comment]
Are you sure this is the full error?

**Comment by BlueTree242** [comment]
Download a development build from [here](https://ci.bluetree242.tk/job/DiscordSRVUtils) and the startup error will be replaced with a debug report, please send it here

**Comment by ElTuna** [comment]
latest was made 7 days ago... is it??

**Comment by BlueTree242** [comment]
yes, that's right

**Comment by ElTuna** [comment]
you mean this??
```
[16:50:33] [Server thread/INFO]: [DiscordSRVUtils] [HikariCP] HikariPool-1 - Starting...
[16:50:34] [DiscordSRV - Initialization/INFO]: [DiscordSRV] [JDA] Login Successful!
[16:50:34] [JDA MainWS-ReadThread/INFO]: [DiscordSRV] [JDA] Connected to WebSocket
[16:50:34] [Server thread/ERROR]: [DiscordSRVUtils] [HikariCP] HikariPool-1 - Exception during pool initialization.
[16:50:34] [Server thread/INFO]: [DiscordSRV] API listener tk.bluetree242.discordsrvutils.listeners.discordsrv.DiscordSRVListener anulado
[16:50:34] [Server thread/WARN]: [DiscordSRVUtils] Plugin could not start
[16:50:36] [Server thread/ERROR]: [DiscordSRVUtils] https://mcdebug.bluetree242.tk/2mnKN#taUUoRCVSMA90mhbO5P56WWbPixJdnsb
[16:50:36] [Server thread/ERROR]: [DiscordSRVUtils] Send this to support at https://discordsrvutils.xyz/support
[16:50:36] [Server thread/WARN]: tk.bluetree242.discordsrvutils.dependencies.hikariCP.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure
[16:50:36] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664)
[16:50:36] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[16:50:36] [Server thread/WARN]:     at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[16:50:36] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
[16:50:36] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[16:50:36] [Server thread/WARN]:     at java.base/java.lang.Thread.run(Thread.java:833)
[16:50:36] [Server thread/WARN]: Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
[16:50:36] [Server thread/WARN]: 
[16:50:36] [Server thread/WARN]: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[16:50:36] [Server thread/WARN]:     at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
```

**Comment by BlueTree242** [comment]
It looks like you are using mysql, and plugin is unable to connect, this isn't an issue with the plugin it's your database.
